
"""create follows table

Revision ID: baad22e76766
Revises: 
Create Date: 2026-06-05 14:53:55.444301

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'baad22e76766'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_index('ix_follows_followed_id', 'follows', ['followed_id'], unique=False)
    op.create_index('ix_follows_follower_id', 'follows', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_follower_id', table_name='follows')
    op.drop_index('ix_follows_followed_id', table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###